'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Eye, EyeOff, KeyRound, Loader2, LockKeyhole, X } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { authResetPassword, authVerifyResetToken } from '@/lib/authApi';
import { ApiError } from '@/lib/api';
import VantaLogo from '@/components/ui/VantaLogo';

export default function ResetPasswordPage() {
  const params = useSearchParams(); const token = params.get('token') || '';
  const [validating, setValidating] = useState(true); const [valid, setValid] = useState(false); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState('');
  const strength = useMemo(() => [password.length >= 8, /[A-Z]/.test(password) && /[a-z]/.test(password), /\d/.test(password), /[^A-Za-z0-9]/.test(password)].filter(Boolean).length, [password]);
  useEffect(() => { if (!token) { setError('This reset link is missing or invalid.'); setValidating(false); return; } authVerifyResetToken(token).then(() => setValid(true)).catch(() => setError('This reset link is invalid or has expired. Request a new one.')).finally(() => setValidating(false)); }, [token]);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); if (password.length < 8) return setError('Use at least 8 characters.'); if (password !== confirm) return setError("Passwords don't match."); setBusy(true); try { await authResetPassword(token, password); setDone(true); } catch (err) { setError(err instanceof ApiError ? err.message : err instanceof Error ? err.message : 'Unable to reset password.'); } finally { setBusy(false); } };
  return <main className="auth-page"><div className="auth-layout" style={{ display:'block', maxWidth:560 }}><div className="auth-mobile-logo" style={{ display:'flex', marginBottom:25 }}><Link className="auth-logo" href="/"><span className="auth-logo-mark"><VantaLogo size={28}/></span>VANTA</Link></div><section className="auth-card" style={{ maxWidth:'none', margin:'auto' }}>{done ? <div style={{ textAlign:'center', padding:'20px 0' }}><CheckCircle2 size={48} color="#62dfbd" style={{ margin:'0 auto 18px' }}/><h2>Password updated</h2><p className="auth-hint" style={{ display:'block', margin:'10px 0 25px' }}>Your account is secure again. You can now sign in with your new password.</p><Link className="auth-submit" style={{ display:'flex', alignItems:'center', justifyContent:'center', textDecoration:'none' }} href="/login">Back to login</Link></div> : <><header><span className="auth-kicker">VANTA / ACCOUNT RECOVERY</span><h2>Set a new password</h2><p>Create a strong password you will remember.</p></header>{(error || validating) && <div className={validating ? 'auth-success' : 'auth-error'} role={validating ? undefined : 'alert'}>{validating ? <><Loader2 className="spin" size={14}/> Checking reset link…</> : <><X size={15} style={{ verticalAlign:'-3px', marginRight:7 }}/>{error}</>}</div>}{valid && <form className="auth-form" onSubmit={submit} style={{ marginTop:16 }}><div className="auth-field"><label htmlFor="new-password">New password</label><div className="auth-input-wrap"><KeyRound size={16}/><input id="new-password" type={show ? 'text' : 'password'} className="auth-input has-action" value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" required/><button type="button" className="auth-password-toggle" onClick={() => setShow(v => !v)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div><div className="auth-strength">{[1,2,3,4].map(n => <i className={n <= strength ? 'on' : ''} key={n}/>)}</div></div><div className="auth-field"><label htmlFor="confirm-password">Confirm new password</label><div className="auth-input-wrap"><LockKeyhole size={16}/><input id="confirm-password" type={show ? 'text' : 'password'} className="auth-input" value={confirm} onChange={e => setConfirm(e.target.value)} autoComplete="new-password" required/></div></div><button className="auth-submit" disabled={busy}>{busy ? <><Loader2 className="spin" size={16}/> Updating…</> : 'Update password'}</button></form>}<div className="auth-switch"><Link className="auth-link" href="/login"><ArrowLeft size={13} style={{ verticalAlign:'-2px' }}/> Back to login</Link></div></>}</section></div></main>;
}