// vanta-gifts.ts

export type GiftCategory =
  | "popular"
  | "premium"
  | "luxury";

export type GiftRarity =
  | "common"
  | "uncommon"
  | "premium"
  | "epic"
  | "luxury"
  | "legendary"
  | "mythic";

export interface VantaGift {
  id: string;
  name: string;
  price: number;
  currency: "VANTA";
  category: GiftCategory;
  rarity: GiftRarity;
  icon: string;
  animationKey: string;
  soundKey: string;
  durationMs: number;
  featured: boolean;
  active: boolean;
}

export const VANTA_GIFTS: VantaGift[] = [
  // ─────────────────────────────────────────────
  // CLASSIC / SOCIAL
  // ─────────────────────────────────────────────

  {
    id: "heart",
    name: "Heart",
    price: 10,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "heart",
    animationKey: "gift-heart",
    soundKey: "gift-soft-pop",
    durationMs: 2500,
    featured: true,
    active: true,
  },
  {
    id: "thumbs-up",
    name: "Thumbs Up",
    price: 5,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "thumbs-up",
    animationKey: "gift-thumbs-up",
    soundKey: "gift-pop",
    durationMs: 2000,
    featured: true,
    active: true,
  },
  {
    id: "this-is-fire",
    name: "This Is Fire",
    price: 10,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "fire",
    animationKey: "gift-fire",
    soundKey: "gift-fire",
    durationMs: 2500,
    featured: true,
    active: true,
  },
  {
    id: "rose",
    name: "Rose",
    price: 25,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "rose",
    animationKey: "gift-rose",
    soundKey: "gift-bloom",
    durationMs: 3000,
    featured: true,
    active: true,
  },
  {
    id: "coffee",
    name: "Coffee",
    price: 50,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "coffee",
    animationKey: "gift-coffee",
    soundKey: "gift-soft-pop",
    durationMs: 3000,
    featured: false,
    active: true,
  },
  {
    id: "balloon",
    name: "Balloon",
    price: 100,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "balloon",
    animationKey: "gift-balloon",
    soundKey: "gift-celebration",
    durationMs: 3500,
    featured: true,
    active: true,
  },
  {
    id: "love",
    name: "Love",
    price: 50,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "love",
    animationKey: "gift-love",
    soundKey: "gift-heart",
    durationMs: 3000,
    featured: true,
    active: true,
  },
  {
    id: "teddy-bear",
    name: "Teddy Bear",
    price: 250,
    currency: "VANTA",
    category: "popular",
    rarity: "premium",
    icon: "teddy-bear",
    animationKey: "gift-teddy-bear",
    soundKey: "gift-cute",
    durationMs: 4000,
    featured: true,
    active: true,
  },
  {
    id: "happy-day",
    name: "Happy Day",
    price: 100,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "sun",
    animationKey: "gift-happy-day",
    soundKey: "gift-celebration",
    durationMs: 3000,
    featured: false,
    active: true,
  },
  {
    id: "cake",
    name: "Cake",
    price: 500,
    currency: "VANTA",
    category: "popular",
    rarity: "premium",
    icon: "cake",
    animationKey: "gift-cake",
    soundKey: "gift-celebration",
    durationMs: 4000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // LUXURY / STATUS
  // ─────────────────────────────────────────────

  {
    id: "fancy-pearl",
    name: "Fancy Pearl",
    price: 250,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "pearl",
    animationKey: "gift-fancy-pearl",
    soundKey: "gift-luxury",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "diamond",
    name: "Diamond",
    price: 1000,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "diamond",
    animationKey: "gift-diamond",
    soundKey: "gift-diamond",
    durationMs: 4000,
    featured: true,
    active: true,
  },
  {
    id: "first-place",
    name: "1st Place",
    price: 500,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "first-place",
    animationKey: "gift-first-place",
    soundKey: "gift-victory",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "crown",
    name: "Crown",
    price: 2500,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "crown",
    animationKey: "gift-crown",
    soundKey: "gift-royal",
    durationMs: 5000,
    featured: true,
    active: true,
  },
  {
    id: "lets-ride",
    name: "Let's Ride",
    price: 1000,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "vehicle",
    animationKey: "gift-lets-ride",
    soundKey: "gift-engine",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "sports-car",
    name: "Sports Car",
    price: 5000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "sports-car",
    animationKey: "gift-sports-car",
    soundKey: "gift-supercar",
    durationMs: 5000,
    featured: true,
    active: true,
  },
  {
    id: "gold-medal",
    name: "Gold Medal",
    price: 1500,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "gold-medal",
    animationKey: "gift-gold-medal",
    soundKey: "gift-victory",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "rocket",
    name: "Rocket",
    price: 10000,
    currency: "VANTA",
    category: "luxury",
    rarity: "legendary",
    icon: "rocket",
    animationKey: "gift-rocket",
    soundKey: "gift-rocket-launch",
    durationMs: 6000,
    featured: true,
    active: true,
  },
  {
    id: "elite-status",
    name: "Elite Status",
    price: 2000,
    currency: "VANTA",
    category: "luxury",
    rarity: "epic",
    icon: "elite-status",
    animationKey: "gift-elite-status",
    soundKey: "gift-status",
    durationMs: 5000,
    featured: true,
    active: true,
  },
  {
    id: "yacht",
    name: "Yacht",
    price: 25000,
    currency: "VANTA",
    category: "luxury",
    rarity: "legendary",
    icon: "yacht",
    animationKey: "gift-yacht",
    soundKey: "gift-luxury",
    durationMs: 7000,
    featured: true,
    active: true,
  },
  {
    id: "ice-diamond",
    name: "Ice Diamond",
    price: 2500,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "ice-diamond",
    animationKey: "gift-ice-diamond",
    soundKey: "gift-ice",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "castle",
    name: "Castle",
    price: 50000,
    currency: "VANTA",
    category: "luxury",
    rarity: "mythic",
    icon: "castle",
    animationKey: "gift-castle",
    soundKey: "gift-mythic",
    durationMs: 8000,
    featured: true,
    active: true,
  },
  {
    id: "pure-royalty",
    name: "Pure Royalty",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "royalty",
    animationKey: "gift-pure-royalty",
    soundKey: "gift-royal",
    durationMs: 6000,
    featured: true,
    active: true,
  },
  {
    id: "galaxy",
    name: "Galaxy",
    price: 100000,
    currency: "VANTA",
    category: "luxury",
    rarity: "mythic",
    icon: "galaxy",
    animationKey: "gift-galaxy",
    soundKey: "gift-cosmic",
    durationMs: 10000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // ROMANTIC / FLORAL
  // ─────────────────────────────────────────────

  {
    id: "neon-flare",
    name: "Neon Flare",
    price: 15,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "neon-flare",
    animationKey: "gift-neon-flare",
    soundKey: "gift-neon",
    durationMs: 2000,
    featured: false,
    active: true,
  },
  {
    id: "ember-orbit",
    name: "Ember Orbit",
    price: 20,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "ember-orbit",
    animationKey: "gift-ember-orbit",
    soundKey: "gift-ember",
    durationMs: 2500,
    featured: false,
    active: true,
  },
  {
    id: "solar-cinder",
    name: "Solar Cinder",
    price: 25,
    currency: "VANTA",
    category: "popular",
    rarity: "common",
    icon: "solar-cinder",
    animationKey: "gift-solar-cinder",
    soundKey: "gift-spark",
    durationMs: 3000,
    featured: false,
    active: true,
  },
  {
    id: "crimson-bloom",
    name: "Crimson Bloom",
    price: 50,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "crimson-bloom",
    animationKey: "gift-crimson-bloom",
    soundKey: "gift-bloom",
    durationMs: 3000,
    featured: false,
    active: true,
  },
  {
    id: "velvet-rose",
    name: "Velvet Rose",
    price: 75,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "velvet-rose",
    animationKey: "gift-velvet-rose",
    soundKey: "gift-rose",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "aurora-petal",
    name: "Aurora Petal",
    price: 100,
    currency: "VANTA",
    category: "premium",
    rarity: "uncommon",
    icon: "aurora-petal",
    animationKey: "gift-aurora-petal",
    soundKey: "gift-aurora",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "prism-kiss",
    name: "Prism Kiss",
    price: 150,
    currency: "VANTA",
    category: "premium",
    rarity: "uncommon",
    icon: "prism-kiss",
    animationKey: "gift-prism-kiss",
    soundKey: "gift-love",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "luminous-embrace",
    name: "Luminous Embrace",
    price: 200,
    currency: "VANTA",
    category: "premium",
    rarity: "uncommon",
    icon: "luminous-embrace",
    animationKey: "gift-luminous-embrace",
    soundKey: "gift-love",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "starry-love",
    name: "Starry Love",
    price: 250,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "starry-love",
    animationKey: "gift-starry-love",
    soundKey: "gift-cosmic-love",
    durationMs: 5000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // CELEBRATION
  // ─────────────────────────────────────────────

  {
    id: "confetti-rocket",
    name: "Confetti Rocket",
    price: 50,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "confetti-rocket",
    animationKey: "gift-confetti-rocket",
    soundKey: "gift-celebration",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "aurora-party",
    name: "Aurora Party",
    price: 100,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "aurora-party",
    animationKey: "gift-aurora-party",
    soundKey: "gift-party",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "celebration-orb",
    name: "Celebration Orb",
    price: 250,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "celebration-orb",
    animationKey: "gift-celebration-orb",
    soundKey: "gift-celebration",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "moon-shell",
    name: "Moon Shell",
    price: 300,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "moon-shell",
    animationKey: "gift-moon-shell",
    soundKey: "gift-mystical",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "iridescent-relic",
    name: "Iridescent Relic",
    price: 400,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "iridescent-relic",
    animationKey: "gift-iridescent-relic",
    soundKey: "gift-relic",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "tide-pearl",
    name: "Tide Pearl",
    price: 500,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "tide-pearl",
    animationKey: "gift-tide-pearl",
    soundKey: "gift-ocean",
    durationMs: 5000,
    featured: false,
    active: true,
  },

  // ─────────────────────────────────────────────
  // CHAMPION / ACHIEVEMENT
  // ─────────────────────────────────────────────

  {
    id: "champion-ribbon",
    name: "Champion Ribbon",
    price: 350,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "champion-ribbon",
    animationKey: "gift-champion-ribbon",
    soundKey: "gift-victory",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "victory-medallion",
    name: "Victory Medallion",
    price: 500,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "victory-medallion",
    animationKey: "gift-victory-medallion",
    soundKey: "gift-victory",
    durationMs: 5000,
    featured: true,
    active: true,
  },
  {
    id: "diamond-league",
    name: "Diamond League",
    price: 750,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "diamond-league",
    animationKey: "gift-diamond-league",
    soundKey: "gift-victory",
    durationMs: 5000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // VEHICLES / TRAVEL
  // ─────────────────────────────────────────────

  {
    id: "hyper-roadster",
    name: "Hyper Roadster",
    price: 1000,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "hyper-roadster",
    animationKey: "gift-hyper-roadster",
    soundKey: "gift-supercar",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "aurora-coupe",
    name: "Aurora Coupe",
    price: 1250,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "aurora-coupe",
    animationKey: "gift-aurora-coupe",
    soundKey: "gift-engine",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "velocity-x",
    name: "Velocity X",
    price: 1500,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "velocity-x",
    animationKey: "gift-velocity-x",
    soundKey: "gift-speed",
    durationMs: 5000,
    featured: true,
    active: true,
  },
  {
    id: "skyline-jet",
    name: "Skyline Jet",
    price: 1000,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "skyline-jet",
    animationKey: "gift-skyline-jet",
    soundKey: "gift-jet",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "cloud-nine",
    name: "Cloud Nine",
    price: 1500,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "cloud-nine",
    animationKey: "gift-cloud-nine",
    soundKey: "gift-dream",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "royal-flight",
    name: "Royal Flight",
    price: 2000,
    currency: "VANTA",
    category: "luxury",
    rarity: "epic",
    icon: "royal-flight",
    animationKey: "gift-royal-flight",
    soundKey: "gift-royal",
    durationMs: 6000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // ICE / ROYAL
  // ─────────────────────────────────────────────

  {
    id: "frost-prism",
    name: "Frost Prism",
    price: 1000,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "frost-prism",
    animationKey: "gift-frost-prism",
    soundKey: "gift-ice",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "glacier-shard",
    name: "Glacier Shard",
    price: 1500,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "glacier-shard",
    animationKey: "gift-glacier-shard",
    soundKey: "gift-ice",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "polar-star",
    name: "Polar Star",
    price: 2000,
    currency: "VANTA",
    category: "luxury",
    rarity: "epic",
    icon: "polar-star",
    animationKey: "gift-polar-star",
    soundKey: "gift-cosmic",
    durationMs: 6000,
    featured: false,
    active: true,
  },
  {
    id: "solar-crown",
    name: "Solar Crown",
    price: 1500,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "solar-crown",
    animationKey: "gift-solar-crown",
    soundKey: "gift-royal",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "empire-crown",
    name: "Empire Crown",
    price: 2000,
    currency: "VANTA",
    category: "luxury",
    rarity: "epic",
    icon: "empire-crown",
    animationKey: "gift-empire-crown",
    soundKey: "gift-royal",
    durationMs: 6000,
    featured: true,
    active: true,
  },
  {
    id: "celestial-crown",
    name: "Celestial Crown",
    price: 2500,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "celestial-crown",
    animationKey: "gift-celestial-crown",
    soundKey: "gift-cosmic",
    durationMs: 7000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // COSMIC / FUTURISTIC
  // ─────────────────────────────────────────────

  {
    id: "crystal-star",
    name: "Crystal Star",
    price: 50,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "crystal-star",
    animationKey: "gift-crystal-star",
    soundKey: "gift-sparkle",
    durationMs: 3000,
    featured: false,
    active: true,
  },
  {
    id: "violet-comet",
    name: "Violet Comet",
    price: 100,
    currency: "VANTA",
    category: "popular",
    rarity: "uncommon",
    icon: "violet-comet",
    animationKey: "gift-violet-comet",
    soundKey: "gift-comet",
    durationMs: 4000,
    featured: false,
    active: true,
  },
  {
    id: "quantum-orb",
    name: "Quantum Orb",
    price: 250,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "quantum-orb",
    animationKey: "gift-quantum-orb",
    soundKey: "gift-quantum",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "holo-badge",
    name: "Holo Badge",
    price: 500,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "holo-badge",
    animationKey: "gift-holo-badge",
    soundKey: "gift-hologram",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "plasma-ring",
    name: "Plasma Ring",
    price: 750,
    currency: "VANTA",
    category: "premium",
    rarity: "premium",
    icon: "plasma-ring",
    animationKey: "gift-plasma-ring",
    soundKey: "gift-energy",
    durationMs: 5000,
    featured: false,
    active: true,
  },
  {
    id: "nova-scepter",
    name: "Nova Scepter",
    price: 1000,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "nova-scepter",
    animationKey: "gift-nova-scepter",
    soundKey: "gift-cosmic",
    durationMs: 6000,
    featured: false,
    active: true,
  },
  {
    id: "eclipse-gem",
    name: "Eclipse Gem",
    price: 1250,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "eclipse-gem",
    animationKey: "gift-eclipse-gem",
    soundKey: "gift-eclipse",
    durationMs: 6000,
    featured: false,
    active: true,
  },
  {
    id: "starlight-capsule",
    name: "Starlight Capsule",
    price: 1500,
    currency: "VANTA",
    category: "premium",
    rarity: "epic",
    icon: "starlight-capsule",
    animationKey: "gift-starlight-capsule",
    soundKey: "gift-starlight",
    durationMs: 6000,
    featured: false,
    active: true,
  },
  {
    id: "infinite-spark",
    name: "Infinite Spark",
    price: 2000,
    currency: "VANTA",
    category: "luxury",
    rarity: "epic",
    icon: "infinite-spark",
    animationKey: "gift-infinite-spark",
    soundKey: "gift-cosmic",
    durationMs: 7000,
    featured: true,
    active: true,
  },
  {
    id: "galaxy-crest",
    name: "Galaxy Crest",
    price: 2500,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "galaxy-crest",
    animationKey: "gift-galaxy-crest",
    soundKey: "gift-cosmic",
    durationMs: 7000,
    featured: true,
    active: true,
  },
  {
    id: "cosmic-wings",
    name: "Cosmic Wings",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "cosmic-wings",
    animationKey: "gift-cosmic-wings",
    soundKey: "gift-cosmic",
    durationMs: 7000,
    featured: true,
    active: true,
  },

  // ─────────────────────────────────────────────
  // MYTHIC
  // ─────────────────────────────────────────────

  {
    id: "phoenix-flame",
    name: "Phoenix Flame",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "phoenix-flame",
    animationKey: "gift-phoenix-flame",
    soundKey: "gift-phoenix",
    durationMs: 8000,
    featured: true,
    active: true,
  },
  {
    id: "royal-dragon",
    name: "Royal Dragon",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "royal-dragon",
    animationKey: "gift-royal-dragon",
    soundKey: "gift-dragon",
    durationMs: 8000,
    featured: true,
    active: true,
  },
  {
    id: "aurora-castle",
    name: "Aurora Castle",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "aurora-castle",
    animationKey: "gift-aurora-castle",
    soundKey: "gift-mythic",
    durationMs: 8000,
    featured: true,
    active: true,
  },
  {
    id: "platinum-throne",
    name: "Platinum Throne",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "platinum-throne",
    animationKey: "gift-platinum-throne",
    soundKey: "gift-royal",
    durationMs: 8000,
    featured: true,
    active: true,
  },
  {
    id: "time-crystal",
    name: "Time Crystal",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "time-crystal",
    animationKey: "gift-time-crystal",
    soundKey: "gift-time",
    durationMs: 8000,
    featured: false,
    active: true,
  },
  {
    id: "nebula-heart",
    name: "Nebula Heart",
    price: 3000,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "nebula-heart",
    animationKey: "gift-nebula-heart",
    soundKey: "gift-cosmic-love",
    durationMs: 8000,
    featured: true,
    active: true,
  },
  {
    id: "lunar-rose",
    name: "Lunar Rose",
    price: 2000,
    currency: "VANTA",
    category: "luxury",
    rarity: "epic",
    icon: "lunar-rose",
    animationKey: "gift-lunar-rose",
    soundKey: "gift-moonlight",
    durationMs: 7000,
    featured: false,
    active: true,
  },
  {
    id: "golden-horizon",
    name: "Golden Horizon",
    price: 2500,
    currency: "VANTA",
    category: "luxury",
    rarity: "luxury",
    icon: "golden-horizon",
    animationKey: "gift-golden-horizon",
    soundKey: "gift-golden",
    durationMs: 8000,
    featured: true,
    active: true,
  },
];

// ─────────────────────────────────────────────
// LOOKUP HELPERS
// ─────────────────────────────────────────────

export const VANTA_GIFT_MAP = Object.fromEntries(
  VANTA_GIFTS.map((gift) => [gift.id, gift])
) as Record<string, VantaGift>;

export function getGiftById(id: string): VantaGift | undefined {
  return VANTA_GIFT_MAP[id];
}

export function getGiftsByCategory(
  category: GiftCategory
): VantaGift[] {
  return VANTA_GIFTS.filter(
    (gift) => gift.active && gift.category === category
  );
}

export function getGiftsByRarity(
  rarity: GiftRarity
): VantaGift[] {
  return VANTA_GIFTS.filter(
    (gift) => gift.active && gift.rarity === rarity
  );
}

export function getFeaturedGifts(): VantaGift[] {
  return VANTA_GIFTS.filter(
    (gift) => gift.active && gift.featured
  );
}

export function searchVantaGifts(query: string): VantaGift[] {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return VANTA_GIFTS.filter((gift) => gift.active);
  }

  return VANTA_GIFTS.filter(
    (gift) =>
      gift.active &&
      gift.name.toLowerCase().includes(normalized)
  );
}